#!/bin/bash

source ./variables.sh

if [ -z "$1" ]; then
    echo "Usage: $0 <project-name>"
    exit 1
fi

PROJECT_NAME="$1"
CUSTOM_CONFIG="$2"
FULL_PATH="$REPO_DIR/$PROJECT_NAME"

if [ -d "$FULL_PATH" ]; then
    $SCRIPT_DIR/open-project.sh $PROJECT_NAME $CUSTOM_CONFIG
else
    echo "Project folder '$PROJECT_NAME' does not exist in $REPO_DIR."
    exit 1
fi

