#!/bin/bash

PROJECTS_DIR="${HOME}/devilbox/data/www"

if [ -z "$1" ]; then
    echo "Usage: $0 <project-name>"
    exit 1
fi

PROJECT_NAME="$1"
FULL_PATH="$PROJECTS_DIR/$PROJECT_NAME"

if [ -d "$FULL_PATH" ]; then
    ./open-project.sh $PROJECT_NAME
else
    echo "Project folder '$PROJECT_NAME' does not exist in $PROJECTS_DIR."
    exit 1
fi

