#!/bin/bash

SESSION=$1

tmux new-window -t "$SESSION" -n "jacket-cms" -c ~/devilbox/data/www/jacket-cms
tmux send-keys -t "$SESSION":"jacket-cms" "nvim ." C-m

tmux new-window -t "$SESSION" -n "jacket" -c ~/devilbox/data/www/jacket
tmux send-keys -t "$SESSION":"jacket" "nvim ." C-m

tmux new-window -t "$SESSION" -n "scanstrut" -c ~/devilbox/data/www/scanstrut-web
tmux send-keys -t "$SESSION":"scanstrut" "nvim ." C-m
